In [ ]:
Google NumPy DataFrame Ultraquick Tutorial

In [4]:
# NumPy is a Python library for creating and manipulating vectors and matrices.
import numpy as np

# Call np.array to create a NumPy matrixes with your own hand-picked values. In the following 2 examples we call np.array to initially create a 6 element vector, the one below creates a 3x2 matrix:
oneDimensionalArray = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2])
print (oneDimensionalArray)



[1.2 2.4 3.5 4.7 6.1 7.2]


In [8]:
twoDimensionalArray = np.array([[1,5],[3,8],[11,6]])
print(twoDimensionalArray)

[[ 1  5]
 [ 3  8]
 [11  6]]


In [12]:
zeros=np.zeros # This will populate a matrix with all zeroes
print(zeros)

<built-in function zeros>


In [13]:
ones=np.ones # This will populate a matrix with all ones
print(ones)

In [14]:
sequence_of_integers = np.arange(5, 12) # will include lower bound 5, but NOT the upper bound 12
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [18]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[66 71 97 83 80 75]


In [19]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.30160852 0.04947809 0.95781516 0.62705695 0.51669539 0.8305055 ]


In [20]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.30160852 2.04947809 2.95781516 2.62705695 2.51669539 2.8305055 ]


In [21]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.30160852 2.04947809 2.95781516 2.62705695 2.51669539 2.8305055 ]


In [22]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[198 213 291 249 240 225]


In [38]:
import random
noise = random.uniform(-2,2)
print(noise) 

1.8123279911153825


In [ ]:
random.choice(range)

In [39]:
label = (3*noise)+4
print(label)

9.436983973346148


In [ ]:
Google Pandas DataFrame Ultraquick Tutorial

In [40]:
# DataFrame are the central data structure in the pandas API

In [41]:
import numpy as np
import pandas as pd

In [42]:
# Create and populate a 5x2 NumPy array.
my_data = np.array([[0, 3], [10, 7], [20, 9], [30, 14], [40, 15]])

In [43]:
# Create a Python list that holds the names of the two columns.
my_column_names = ['temperature', 'activity']

In [44]:
my_data

array([[ 0,  3],
       [10,  7],
       [20,  9],
       [30, 14],
       [40, 15]])

In [45]:
my_column_names

['temperature', 'activity']

In [46]:
# Create a DataFrame.
my_dataframe = pd.DataFrame(data=my_data, columns=my_column_names)

In [47]:
my_dataframe

temperature  activity
0            0         3
1           10         7
2           20         9
3           30        14
4           40        15

In [48]:
# Create a new column named adjusted.
my_dataframe["adjusted"] = my_dataframe["activity"] + 2

# Print the entire DataFrame
print(my_dataframe)

   temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11
3           30        14        16
4           40        15        17


In [50]:
# rows 0-2
my_dataframe.head(3)

temperature  activity  adjusted
0            0         3         5
1           10         7         9
2           20         9        11

In [52]:
# row 2
my_dataframe.iloc[[2]]

temperature  activity  adjusted
4           40        15        17

In [53]:
# rows 1-3
my_dataframe[1:4]

temperature  activity  adjusted
1           10         7         9
2           20         9        11
3           30        14        16

In [54]:
# print temperature column
my_dataframe['temperature']

0     0
1    10
2    20
3    30
4    40
Name: temperature, dtype: int64